services:
  rclone-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: zzmrclone-manager:api-local
    container_name: rclone-manager
    restart: unless-stopped
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - "6050:80"
    volumes:
      - ./data:/app/data
      - /root/.config/rclone:/root/.config/rclone
      - ./logs:/app/logs
      # 映射你要监控的本机目录
      # 示例：
      #- /opt:/opt
      # 云盘挂载如果要让宿主机可见，请自行映射，例如：
      #- type: bind
      #  source: /data/cloud-mount
      #  target: /data/cloud-mount
      #  bind:
      #    propagation: rshared
